### ISSUE TITLE
Convertendo o arquivo "alien_invasion.py" em um arquivo .exe.

### ISSUE THREAD

**Issue by joaotinti75** [RodrigoAP1307/ALIEN_INVASION#2]
**Parabéns pelo trabalho Rodrigo!** Gostaria de deixar uma sugestão. 
Para que qualquer pessoa possa jogar o game que você criou, você pode converter o seu arquivo "alien_invasion.py" em um arquivo .exe, dessa forma, a pessoa não vai precisar instalar o python e nem o pygame para poder jogar.
Aqui um link de como fazer isso: [link](https://www.youtube.com/watch?v=1yLI2Uyl4T4)

**Comment by RodrigoPiropo** [comment]
Muito obrigado @joaotinti75 pela sugestão! Fiquei com receio de fazer isso devido a própia natureza do python que não é uma linguagem para gerar exe...
Mais irei tentar fazer isso quando o jogo estiver pronto... 👍
